sonar.projectKey=L01-123456789_W8
sonar.organization=l01-123456789

sonar.host.url=https://sonarcloud.io

sonar.projectName=W8
sonar.projectVersion=1.0

sonar.sources=app
sonar.coverage.exclusions=app/assets/**, app/core/theme.js
sonar.sourceEncoding=UTF-8

# coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
